// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTBAMTdtPlAU9Jj1s0hewuQxwbdYhjUJg',
    appId: '1:674327372383:web:0d89943415e8678b5ff1ea',
    messagingSenderId: '674327372383',
    projectId: 'finalproject-34930',
    authDomain: 'finalproject-34930.firebaseapp.com',
    storageBucket: 'finalproject-34930.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBi2NJM1-Lz4WfnCJlTlCWsinyXti3mlok',
    appId: '1:674327372383:android:f0bc10a8587cbcda5ff1ea',
    messagingSenderId: '674327372383',
    projectId: 'finalproject-34930',
    storageBucket: 'finalproject-34930.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4RkaAbRDIkwDhczOspqMLUV1Cj8kfr-Y',
    appId: '1:674327372383:ios:747d859e73d122bb5ff1ea',
    messagingSenderId: '674327372383',
    projectId: 'finalproject-34930',
    storageBucket: 'finalproject-34930.appspot.com',
    iosBundleId: 'com.example.finalProject',
  );
}